### ISSUE TITLE
SPEC - document supported path notations for filtering and projection

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#123]
What path notations can be used: 
- "foo"
- "foo.bar"
- any other ways to support sub documents / objects 

we have implemented some of these, task to spec what we should have and check against what we have.

**Comment by amorton** [comment]
I had though there was another nested document path but was wrong.

**Comment by amorton** [comment]
@tatu-at-datastax  and @maheshrajamani could you please take a look at the commit here and see if that covers the paths we support https://github.com/stargate/jsonapi/commit/7fb03f87d5af1dcb0fbf42198a3836d906a476c8

I dont think there will be any code changes, if there are can you create new tickets for them.

there is another ticket that will have the rules for document.

**Comment by amorton** [comment]
Spec updated, ticket created for any server side work (#171) and feature matrix updated

**Comment by tatu-at-datastax** [comment]
Ok, so this ticket covers 2 of 3 use cases; separate tickets exist for update operations.

Note that implementations for all 3 use cases are separate by necessity. Filtering works by virtue of shredding producing matching paths. Projection will need more work, unrelated to filtering.
