### ISSUE TITLE
Ensure _id is always the first field in the document

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#126]
_id must always be the first field in the document, this should apply in all cases. 

Situations where _id may be modified or created or need to be checked: 

- document insertion, _id may be anywhere 
- new document and we create the _id
- update operations where fields are added or removed 

This refers to the the default projection view, where no projection is specified. If projection is specified we use the order in the projection clause.

**Comment by tatu-at-datastax** [comment]
This is being taken care of during creation by shredder; `_id` is indeed picked up and relocated if need be (including generation).

`$set` and `$unset` operations also prevent changes to `_id` as per Mongo limitations.

**Comment by tatu-at-datastax** [comment]
@amorton Aside from 3 cases mentioned, can we think of others to verify?

**Comment by amorton** [comment]
@tatu-at-datastax as for other operations, I think it should be illegal to run any Update Operations on the `_id` as it is immutable

**Comment by tatu-at-datastax** [comment]
I added explicit checks for all 5 supported update operators so that they cannot modify `_id`.
Since creation enforces "_id is always the first field" -- including upserts -- I think this is complete now.
