### ISSUE TITLE
SPEC - Document that we maintain field order 

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#129]
We do this easily now because we are storing the JSOn as a blob. 

What are the places where field order changes ? 
- _id moved to first 
- set and unset ?

Check with @tatu-at-datastax  any other exceptions.

**Comment by tatu-at-datastax** [comment]
We do maintain document order for all update operations I am aware of: modifications start with originally provided document (from `doc_json` column) and new entries are appended at the end of Object values (unless replacing existing values).
And yes, one (and only) thing wrt order we do change is to move `_id` as the first field (or add as first if not provided).

It is possible to change order with a sequence of `$set` and `$unset` operations, although not with a single update operation (not legal to use both for same field).

**Comment by tatu-at-datastax** [comment]
Document order maintained throughout processing; no known deviations, only changes due to logical renames etc handling that is implemented as combination of delete + insert. Closing.
