### ISSUE TITLE
SPEC - Document using $slice in projections 

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#130]
Update spec for projections here https://github.com/stargate/jsonapi/blob/main/docs/jsonapi-spec.textile#clauseProjection

to support using $slice on arrays, we want to avoid needing to implement filter queries against arrays in memory for now. 

$slice will work like python slicing. 

UNKNOWN: support for nested arrays, need to understand if we want to support nested arrays

**Comment by tatu-at-datastax** [comment]
Like all projections, we implement this on JSON API side, not as part of CQL queries.
Implementation handled under #329.
