### ISSUE TITLE
Ensure nextPageState in requests is handled securely 

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#139]
find command supports next page state, as a UU encoded blob of the binary blob we get from Cassandra. 

This is data we sent back to the client, so it may be modified and re-sent in some corrupted way.  

Is there any checksum or validation can do before UU decoding or before sending to C* ? 
Is this a potential attack vector, we are sending untyped binary into C* which it is treating as a byte buffer. We should check with core DB if there has been any security assesment.

**Comment by maheshrajamani** [comment]
@amorton This is handled in the stargate coordinator where we incoming pagingState value is deserialized to PagingState.

**Comment by amorton** [comment]
>This is handled in the stargate coordinator where we incoming pagingState value is deserialized to PagingState.
The question is how it is handled, is it done in a secure way? I suspect that the original design and implementation of paging in C* via the native binary protocol (which is what we end up using) did not expect the pagination token to be handed outside of the application and assumed it as somewhat trusted inout. So may not have checked if the token had been tampered with in any way. The tampering could lead to either a fault, or a buffer overrun style attack, or access to data that was not expected (doubtfull, this is just the style of attack this opens). 

In modern C* the paging state has encoded partition key (single single partition reads) and cluster key values. The clustering key values are decoded against the current (in memory on the node) meta data for the clustering keys on the table. I was thinking about what would happen if the token handed back was altered and then went through this process. These code paths seem to trust the input as I think they are mostly used when reading data from disk. 

I have poked into the code, and need to dive in further. At first glance i did not see a checksum or verification process but I will need to look further. 

Relevant sections in
 [PagingState.deserialize()](https://github.com/apache/cassandra/blob/91f6a9aca8d3c22a03e68aa901a0b154d960ab07/src/java/org/apache/cassandra/service/pager/PagingState.java#L89)

and 

[PageState.RowMark.clustering()](https://github.com/apache/cassandra/blob/91f6a9aca8d3c22a03e68aa901a0b154d960ab07/src/java/org/apache/cassandra/service/pager/PagingState.java#L410)

Next action is for me to read the code further to see if there is a vector and ask someone else in the DB on their thoughts.
