### ISSUE TITLE
Allow insert of an empty document using insertOne

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#140]
insertOne should support accepting a totally empty document {} , we then add the _id and insert,. 

This may be existing behaviour, we need to confirm and then ensure if documented in spec and examples.

**Comment by maheshrajamani** [comment]
@amorton Inserting empty document is already supported.
Request:
`{
  "insertOne": {
    "document" : {}
  }
}`

Response:
`{
  "status": {
     "insertedIds": [
        "df69c205-22ba-4d08-9458-06873b3f5103"
     ],
  }
}`

**Comment by maheshrajamani** [comment]
Closing the issue as it works.
