### ISSUE TITLE
Limit number of documents for deleteMany and updateMany commands

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#145]
We need some sort of limit, set it to 10 for now and make it configurable. 

When done, pass the ticket back and we will update the spec.

**Comment by ivansenic** [comment]
* So we are agreeing on setting a limit here? It will not handle all the document that need to be updated/delete in one single request? 
* What are the consequences for the user side here?
* @maheshrajamani said if we choose this, we should inform use if there is more documents to process
* Configurable options sound good if we decide to go this way.

**Comment by maheshrajamani** [comment]
> * @maheshrajamani said if we choose this, we should inform use if there is more documents to process

Yes, Application reads for document keys to delete or update, Once limit number of records is processed, the paging state from the last read can be returned to the driver to inform Database has more records that satisfies this condition.
