### ISSUE TITLE
SPEC document countDocuments()

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#147]
Talk to @maheshrajamani - what are the limitations on the filters etc. 

What are the performance problems. 
Should we also ask core DB for estimated count ?

**Comment by maheshrajamani** [comment]
@amorton estimatedDocumentCount() returns document based on metadata without filter. 
In cassandra, below command should provide this approximate value. As per this [link](https://stackoverflow.com/questions/71644325/what-is-system-size-estimates-in-cassandra-and-plausible-reasons-behind-high-dis) it's updated every 5 mins.
select sum(partitions_count) from system.size_estimates where keyspace_name = 'docsapi' and table_name = 'test';
Issue here is Astra doesn't allow queries to system keyspace. Could be a good discussion to ask core DB.
