### ISSUE TITLE
Ensure namespace and collection names are validated

### ISSUE THREAD

**Issue by ivansenic** [stargate/jsonapi#149]
Only allow names that C* would allow. Add validation to the commands. Improve URI path patterns to include the validation as well, or maybe simply validate `CommandContext` that's being passed to the `CommandProcessor`.

**Comment by ivansenic** [comment]
@maheshrajamani what reserved words are you referring to, I was checking this:

```
Keyspace names can have up to 48 alpha-numeric characters and contain underscores; only letters and numbers are supported as the first character. Cassandra forces keyspace names to lowercase when entered without quotes. 
```

**Comment by maheshrajamani** [comment]
The issue states "Only allow names that C* would allow. ". I was checking if more validation is needed with cassandra reserved words. 
Eg: `create table select (col1 text PRIMARY KEY , col2 text);
SyntaxException: line 1:13 no viable alternative at input 'select' (create table [select]...)`

But with the change done to enclose collection names with quotes this should be handled.
Eg: `create table "select" (col1 text PRIMARY KEY , col2 text);`

Think we can close this issue.

**Comment by ivansenic** [comment]
I still need to enforce validation on the path parameters. Will do this and resolve it.
