### ISSUE TITLE
Design + Spec service side implementation of sort + offset

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#156]
Ticket to collect design ideas for how we can implement this in the API tier

- sort on a single field 
- what restrictions do we have on the field, e.g. can you sort on an element in an array ? 
- how will we do the sort in memory, do we need to fully deserialise the whole document or can we (sometimes or all the time) use the values in the table columns ? 
- What is a reasonable limit for sort ? Based on the number of docs, or the total size of docs ? Do we need to store the byte size of a doc on the row so we know it before deserialising (probably good to know anyway) 
- How do we support cursor based pagination of sorted results? This is different to limit + offset, it is where the requested number of rows (size) is greater than our cursor page size and we need to send the result in multiple responses. Maybe we do not support cursors over sorted results. 

This would be *nice to have* for the demo release, but not at expense of other things working.

**Comment by maheshrajamani** [comment]
@amorton Can this issue be closed?

**Comment by amorton** [comment]
I still need to get the spec up to date

**Comment by vkarpov15** [comment]
Re: last point, I think cursors over sorted results would be a nice to have for GA. I think limit+skip with sorted results is enough for private preview.

Re: point 2, you can sort by array elements, or arrays, in MongoDB. Although in my experience I haven't come across a use case where this particular feature would be useful.

```
MongoDB Enterprise > db.tests.find()
MongoDB Enterprise > db.tests.insertOne({ arr: [1,2] })
{
	"acknowledged" : true,
	"insertedId" : ObjectId("643c9e3e2c97cd1f99f5d16c")
}
MongoDB Enterprise > db.tests.insertOne({ arr: [3,4] })
{
	"acknowledged" : true,
	"insertedId" : ObjectId("643c9e412c97cd1f99f5d16d")
}
MongoDB Enterprise > db.tests.find().sort({ 'arr.0': 1 })
{ "_id" : ObjectId("643c9e3e2c97cd1f99f5d16c"), "arr" : [ 1, 2 ] }
{ "_id" : ObjectId("643c9e412c97cd1f99f5d16d"), "arr" : [ 3, 4 ] }
MongoDB Enterprise > db.tests.find().sort({ 'arr.0': -1 })
{ "_id" : ObjectId("643c9e412c97cd1f99f5d16d"), "arr" : [ 3, 4 ] }
{ "_id" : ObjectId("643c9e3e2c97cd1f99f5d16c"), "arr" : [ 1, 2 ] }
MongoDB Enterprise > db.tests.find().sort({ 'arr': -1 })
{ "_id" : ObjectId("643c9e412c97cd1f99f5d16d"), "arr" : [ 3, 4 ] }
{ "_id" : ObjectId("643c9e3e2c97cd1f99f5d16c"), "arr" : [ 1, 2 ] }
MongoDB Enterprise > db.tests.find().sort({ 'arr': 1 })
{ "_id" : ObjectId("643c9e3e2c97cd1f99f5d16c"), "arr" : [ 1, 2 ] }
{ "_id" : ObjectId("643c9e412c97cd1f99f5d16d"), "arr" : [ 3, 4 ] }
MongoDB Enterprise > 
```

In terms of limits, I think we decided that total size is a reasonable limit.
