### ISSUE TITLE
Implement general update operator `$rename`

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#165]
Another general-purpose array operator to implement is `$rename`. Its semantics are similar to `$unset` followed by `$set` (if that was allowed), so that:

1. If target path exists, the value is overwritten
2. If source path does not exist, operation does nothing (but does not fail)

Format is simple: 

```
{ "$rename" : { "field1" : "newName1", .... , "fieldN", "newNamen" } }
```

Following error modes exist:

1. `_id` either as source or target: cannot modify immutable property "_id"
2. Same source and target (must differ)
3. Attempt to move source to incompatible path

The last case occurs, for example when an attempt is madeto set a property on Array value: that is, target path points to something that is not possible to add: for example with

```
{ "x" : 3, "array" : [ 1 ] }
```

attempt to apply operation

```
{ "$rename" : { "x" : "array.x" }  }
```

would fail. Same is true for paths "through" atomic fields; only (sub)documents have properties.

**Comment by vkarpov15** [comment]
`$rename` isn't necessarily an array operator. I'd also put `$rename` as low priority, it is rarely used in my experience.

**Comment by tatu-at-datastax** [comment]
Thank you @vkarpov15 that was a copy-paste mistake (I know it's not array-specific).

I am creating issues based on @amorton's list; this is lower priority than my current work on dotted paths for sure.
