### ISSUE TITLE
Error message when collection name has invalid chars

### ISSUE THREAD

**Issue by kathirsvn** [stargate/jsonapi#167]
While passing a collection name with invalid characters (for example test/?w.]\`) to the `createCollection` command, instead of getting a proper error message about the collection name, we are getting an error message that partially exposes the create table if not exists statement.

**Request:**
{"createCollection":{"name":"test/?w.`"}}

**Expected response:**
{"errors":["message": "Collection name has invalid characters!"]}

**Actual response:**
{"errors":["message": "INVALID_ARGUMENT: line 1:39 mismatched input '/' expecting '(' (... IF NOT EXISTS testks1.test[/]...)"],"exceptionClass":"StatusRuntimeException"}}

**Comment by ivansenic** [comment]
Fixed in https://github.com/stargate/jsonapi/pull/268
