### ISSUE TITLE
Support dotted notation path in all clauses 

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#171]
Document paths are now defined in the specification here [Document Paths](https://github.com/stargate/jsonapi/blob/main/docs/jsonapi-spec.textile#document-paths) which builds on the def for a field name and array index in the same doc. 

Spec was finished in #123 

This ticket is to confirm they are supported in all places in the query clauses. Spec is not up to date for all clause syntax, but anywhere a command clause can reference a field in the document is probably a Dotted Notation Path

This will include:
- all paths in a filter clause
- projection to include or exclude a field
- paths in a sort clause (to be added) 
- all paths for operators in the update clause. 

@maheshrajamani  and @tatu-at-datastax  this is a catchall for the supported dotted notation, happy for you to close if it is not needed just following up from the spec change. I have updated the feature matrix, dotted paths are listed for the clauses, can you update if they are all done in the server.

**Comment by tatu-at-datastax** [comment]
At this point dotted notation works for:

* Filter clauses
* Update operators (ones supported)

but not on

* Projection
* Sort

as these are not implemented yet.
