### ISSUE TITLE
Implement options for `find` command

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#174]
**EDIT**: as per @ivansenic 's comment, this is about remaining verification of options just for `find` command: other work has been completed.

**Comment by ivansenic** [comment]
Only left thing is `find` command. I will rename this issue. Depends on [#spec](https://github.com/stargate/jsonapi/issues/260)

**Comment by maheshrajamani** [comment]
@ivansenic Can this be closed?

**Comment by ivansenic** [comment]
@maheshrajamani no, not done yet.
