### ISSUE TITLE
Detect change in field order for $set update operator with Object value

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#190]
(follow-up to #166 implementation via #176)

When replacing JSON values with `$set` it is possible to have Object values that are logically same as JSON -- where Object property order is not significant -- but that differ from Mongoose semantic point of view. The current implementation relies on `JsonNode.equals()` which does not consider order significant. We should test that comparison does consider field/property order, however.

Comparison may possible be implemented using `JsonNode` custom comparator functionality:

```java
    public boolean equals(Comparator<JsonNode> comparator, JsonNode other) {
        return comparator.compare(this, other) == 0;
    }
```

or if not, with relatively straight-forward recursive-descent traversal.

**Comment by vkarpov15** [comment]
Good catch. Key order does matter in Mongoose, so it would be good to handle this case. Not critical for alpha though.
