### ISSUE TITLE
Define `status.moreData` in the spec

### ISSUE THREAD

**Issue by ivansenic** [stargate/jsonapi#207]
Currently our code sets the `status.moreData` in case of a `deleteMany|updateMany` commands. I guess other many commands, like update, have the same behavior.

However, there are several unclear things that should be documented and that will help me continue with the #178:

* is the `status.moreData` set to false in case there is no more? currently we don't send this status back at all in case there is no data
* is the `status.moreData` set in case of `deleteOne` command? if so, we would need to change the current logic

**Comment by tatu-at-datastax** [comment]
I am not Aaron, but I think that the current definition is:

1. `status.moreData` is only ever set to `true`, omitted if `false`. Not sure how important exclusion is as caller must only assume more entries available for `true` value; assuming missing means `false`
2. I do not think `status.moreData` should be set for `deleteOne` command, esp. if we default for not including `false` for Many-cases

**Comment by ivansenic** [comment]
@tatu-at-datastax I am fine with that, let's just add this to spec. It's not clear. In fact `moreData` flag is not even mentioned.

**Comment by ivansenic** [comment]
@amorton The current impl after merging #209 is what @tatu-at-datastax described in the comment above. Please add those to the spec. If any code-base changes are needed, please ping me.

**Comment by amorton** [comment]
> status.moreData is only ever set to true, omitted if false. Not sure how important exclusion is as caller must only assume more entries available for true value; assuming missing means false

Correct 

> I do not think status.moreData should be set for deleteOne command, esp. if we default for not including false for Many-cases
Correct, in this case the caller only expected 1 doc to be deleted. It's cases where the number if unlimited we need to do the `moreData` trick. 

@ivansenic  looks good to me.

**Comment by ivansenic** [comment]
@amorton OK can you add this to the spec? the spec does not mention the `status.moreData` at all.. The commands and responses are already implemented as described above, so we just need docs update.

**Comment by ivansenic** [comment]
Missing for the update commands as well, see: https://github.com/stargate/jsonapi/pull/254#issuecomment-1466044413

**Comment by ivansenic** [comment]
Taking over so I can relief @amorton from spec writing a bit.
