### ISSUE TITLE
Numeric Document ID stored as scientific notation in doc json

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#210]
The numeric document _id field is stored in scientific notions in the document json.

`{
  "insertOne": {
    "document": {
      "_id": 30,
      "purchase_type": "Online",
      "customer": {
        "name": "Jim",
        "phone": "123-123-1234",
        "address": {
          "address_line": "1234 Broadway",
          "city": "New York",
          "state": "NY"
        }
      },
      "purchase_date": "12/31/2022",
      "seller": {
        "name": "Jon",
        "location": "New York"
      },
      "items": [
        {
          "car": "BMW",
          "color": "Black"
        },
        "Extended warranty - 5 years"
      ],
      "amount": 65000,
      "status": "active"
    }
  }
}`

Data stored in the doc_json field as `{"_id":3E+1,"purchase_type":"Online","customer":{"name":"Jim","phone":"123-123-1234","address":{"address_line":"1234 Broadway","city":"New York","state":"NY"}},"purchase_date":"12/31/2022","seller":{"name":"Jon","location":"New York"},"items":[{"car":"BMW","color":"Black"},"Extended warranty - 5 years"],"amount":65000,"status":"active"}`

**Comment by tatu-at-datastax** [comment]
Ahhhh. It only happens with trailing zeroes. Good catch.
