### ISSUE TITLE
Setting Serial consistency for write operation

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#238]
All the write operation are run as LWT. This needs Serial consistency to be set.

By default set serial consistency to SERIAL. In case the write consistency is set as LOCAL_QUORUM set the serial consistency to LOCAL_SERIAL.

**Comment by ivansenic** [comment]
@maheshrajamani this can be controlled with the config options.. Do you want to submit a PR for this?

**Comment by maheshrajamani** [comment]
Yes, will do. For this issue, @amorton wanted to understand this fully to set appropriate default value. Maybe I will start with LOCAL_SERIAL as default value in the configuration.

**Comment by maheshrajamani** [comment]
As per this [documentation](https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/dml/dmlConfigSerialConsistency.html) this is required in LWT to achieve linearizable consistency. Default value set to SERIAL. Can be override this using configuration `stargate.queries.serial-consistency`
