### ISSUE TITLE
updateMany 'upsert' flag response fields missing

### ISSUE THREAD

**Issue by kathirsvn** [stargate/jsonapi#273]
While running `updateMany` with `upsert` flag set to `true`, when a record is not found on the db for the given filter, it's expected to insert a new document with the values given in the filter (with eq operator) and the values in the $set operator. Though I could see the record getting upserted into the database, the `upsertedId` and `upsertedCount` fields are not available in the response of the `updateMany` command.

Here are the steps to reproduce:

Create a keyspace
```shell
curl --location 'http://localhost:8080/v1' \
--header 'x-cassandra-token: 3830b533-cb52-4e6b-94f9-52ed4e9bd3ad' \
--header 'Content-Type: application/json' \
--data '{"createNamespace":{"name":"testks1"}}'
```
Create a collection
```shell
curl --location 'http://localhost:8080/v1/testks1' \
--header 'x-cassandra-token: 3830b533-cb52-4e6b-94f9-52ed4e9bd3ad' \
--header 'Content-Type: application/json' \
--data '{"createCollection":{"name":"collection1"}}'
```
Insert a couple of records
```shell
curl --location 'http://localhost:8080/v1/testks1/collection1' \
--header 'x-cassandra-token: 3830b533-cb52-4e6b-94f9-52ed4e9bd3ad' \
--header 'Content-Type: application/json' \
--data '{"insertMany":{"documents":[{"username":"id1","city":"nyc"},{"username":"id2","city":"nyc"}]}}'
```
Execute `updateMany` with `upsert` flag set to `true`
```shell
curl --location 'http://localhost:8080/v1/testks1/collection1' \
--header 'x-cassandra-token: 3830b533-cb52-4e6b-94f9-52ed4e9bd3ad' \
--header 'Content-Type: application/json' \
--data '{"updateMany":{"filter":{"city":"la"},"update":{"$set":{"state":"ca"}},"options":{"upsert":true}}}'
```
Actual Response
```json
{
    "status": {
        "matchedCount": 0,
        "modifiedCount": 0
    }
}
```
Expected Response
```json
{
    "status": {
        "matchedCount": 0,
        "modifiedCount": 0,
        "upsertedId": "object_id_of_the_inserted_record",
        "upsertedCount": 1
    }
}
```

**Comment by kathirsvn** [comment]
Makes sense. I agree that 'upsertedCount' need not be there in the response. Mongoose expects that and I can set that in the driver layer.

**Comment by vkarpov15** [comment]
Yeah `upsertedCount` is unnecessary, `upsertedId` is sufficient for clients to tell whether a document was upserted or not.

Worth clarifying: you cannot upsert multiple documents with `updateMany()`. `updateMany()` with `upsert: true` will upsert at most one document.
