### ISSUE TITLE
Implement `$in` support

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#291]
`{ "find" : { "filter" : { "field" : { "$in" : [1,2] } } } }` finds all documents where `field` is either 1 or 2. Think a "OR" for `$eq`.

It looks like [Mongoose's populate() function](https://mongoosejs.com/docs/populate.html) uses `$in` under the hood, so we'll need this to support populate.

**Comment by amorton** [comment]
Updating from a chat today,. `$in` when used with a single field is (roughly speaking) a compact way to send multiple single field lookups; is something important from populate() in mongoose; and is often used for _id lookups which means we can make them go faster by using the CQL table primary key. 

i.e. `{ "find" : { "filter" : { "_id" : { "$in" : [1,2] } } } }` is asking for the documents with _id 1 and 2. The most efficient way to service this request would be to send multiple async primary key lookups to C*.

**Comment by amorton** [comment]
From chat this morning: 

* We are going to do 1 A below first, then add B as a backlog 
* Create a task to do investigation into 2 and 3

Our target use case is how Mongoose populate uses $IN

Decisions - complexity  
1) support for _id only thing in filter - PRIVATE PREVIEW
{ "filter" : { "_id" : { "$in" : [1,2] } } } 

2) support for _id and other things in filter  - Possible, investigate if we want / need this feature in API these queries can get harder to run 
{ "filter" : { "_id" : { "$in" : [1,2] } }, "eyes" : "red" } 

3) support for all fields - Possible, add later as needed, polymorphic fields makes it harder
{ "filter" : { "eyes" : { "$in" : ["red", "green"] } }} 

Guardrails - when you have _id in the filter 
a) set limit of say 20 - and use CQL IN - DO FIRST, quick release for the populate() Mongoose feature
select * from shred where key IN (1,2);

b) set limit of to prevent abuse - and use multiple statements - Put in backlog, we want to do this, do before GA 
select * from shred where key = 1;
select * from shred where key = 2;

**Comment by maheshrajamani** [comment]
Guardrail B and Complexity 1 and 2 implemented as part of #348

**Comment by maheshrajamani** [comment]
Complexity 3 will be implemented when core DB is done to support `in`.

**Comment by Yuqi-Du** [comment]
resolved 
https://github.com/stargate/stargate/pull/2778
https://github.com/stargate/jsonapi/pull/535
