### ISSUE TITLE
Support empty `options` object for all commands

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#293]
For example, `deleteOne()` currently fails if passed `options`, and Mongoose always sends an empty object `{}` as `options`.

We can work around this issue in stargate-mongoose, but I think it would be better if every command supported passing an `options` object, even if `options` is empty. You can still throw an error if an unsupported option is passed.

Re: https://github.com/stargate/jsonapi/pull/286#issuecomment-1483119673

**Comment by ivansenic** [comment]
I ll take this quickly..
