### ISSUE TITLE
Spec: should `findOne()` have `count` entry in response?

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#313]
Working on #300, I noticed what seems like a minor discrepancy in our spec: inclusion (or not) of `count` property in response for `find()`, `findOne()` and `findOneAndModify()`.
It seems to me that:

* Spec suggests that ONLY `find()` should have it (see https://github.com/stargate/jsonapi/blob/main/docs/jsonapi-spec.textile#commandFind -- "'data' -- Present with fields : docs, count and nextPageState." -- but NOT `findOne()` ("'data' -- Present with fields : docs only"
* Our implementation always adds `count` in `data`, as long as `docs` is a non-null array.

So, it looks like either Spec should be updated to state that `count` is included for `findOne()`/`findOneAndUpdate()` OR our implementation should drop it from them.

**Comment by vkarpov15** [comment]
FWIW, Mongoose doesn't expect a `count` property in the response for `find()`, `findOne()`, or `findOneAndUpdate()`. `count` would be redundant:

1. For `find()`, `count` would just be the length of the result array
2. For `findOne()`, `count` would be 0 or 1 depending on if the result is `null`
3. For `findOneAndUpdate()` without upsert, same as `findOne()`. With `upsert`, depends on `upsertedId`, `returnDocument`, and whether the result is `null`.

**Comment by tatu-at-datastax** [comment]
cc @amorton @maheshrajamani  what do we think here? It is redundant information as @vkarpov15 points out, even for full `find()`.

**Comment by maheshrajamani** [comment]
Don't have a point of view on this. Server is just doing List.size() to get this count. Believe mangoose driver will ignore the information which are not required.

**Comment by tatu-at-datastax** [comment]
I am ok with leaving it there if no one has strong opinions.

**Comment by ivansenic** [comment]
To confirm, task in this issue is to remove `count` in the `findOne` and `findOneAndUpdate` without `upsert`, right?

**Comment by maheshrajamani** [comment]
All findOne* commands return document. So need to do it for the following:
1. findOne
2. findOneAndUpdate
3. findOneAndDelete
4. findOneAndReplace

**Comment by tatu-at-datastax** [comment]
> To confirm, task in this issue is to remove `count` in the `findOne` and `findOneAndUpdate` without `upsert`, right?

It is for dropping it altogether, including case of `upsert`.
