### ISSUE TITLE
Implement findCollections command

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#320]

**Comment by ivansenic** [comment]
Is there any spec for this one? I guess this should return only the valid jsonapi collections, right?

**Comment by maheshrajamani** [comment]
Yes, collections from the provided namespace. There is no spec for it yet.

**Comment by ivansenic** [comment]
@maheshrajamani How important is this? I can take, but not sure I can finish it today.. Let me try..

**Comment by johnsmartco** [comment]
Spec updated in PR https://github.com/stargate/jsonapi/pull/334.  Need +1 approval to merge. cc:  @maheshrajamani
