### ISSUE TITLE
Decide on system and non-jsonapi namespace handling

### ISSUE THREAD

**Issue by ivansenic** [stargate/jsonapi#341]
Currently a user is allowed to drop any namespace using the jsonapi, if the API key permissions would allow it. Similarly, when listing existing namespaces it will list all namespaces, regardless if the tables inside of that namespace are related to jsonapi or not.

We need to decide if we want to limit the scope of the namespace handling from the jsonapi side. Since there are no keyspace metadata that we can add on the creation to "label" a namespace being created from jsonapi we need a different approach. Something that I brought in several other tickets and PRs would be like this:

* Drop
   * allowed if a namespace has not tables
   * allowed if all tables existing in a namespace are jsonapi tables
   * not allowed in any other case
* List, include namespaces that
   * have no tables
   * at least one table is a jsonapi table

**Comment by ivansenic** [comment]
@maheshrajamani @tatu-at-datastax @amorton @jeffreyscarpenter @vkarpov15  Let me know what you think about the proposal above please.

**Comment by vkarpov15** [comment]
I think a more general question is appropriate: how do we want to handle non-jsonapi tables in jsonapi? Suppose you try to use the jsonapi to `find` documents in a table that isn't a jsonapi table, what should happen? Error, no results?

I'll have to think about this a little more, but my immediate reaction is "error", so in that case I think your suggested approach of only allowing `dropNamespace()` if every table is a jsonapi table is reasonable.

**Comment by jeffreyscarpenter** [comment]
I think we should move slowly on this. We will explore what possibilities exist for managing access within the Astra environment first in order to have a complete picture, then we can think about how to approach in both OSS and Astra deployments holistically.

**Comment by ivansenic** [comment]
@jeffreyscarpenter This depends on https://github.com/stargate/jsonapi/pull/340 being merged.. There I introduced a way to check if table schema matches expected jsonapi schema..

**Comment by vkarpov15** [comment]
@ivansenic I was thinking about the "find" case to see what would be a reasonable default behavior, and I think throwing an error when interacting with a non-jsonapi collection is a reasonable default behavior.

**Comment by jeffreyscarpenter** [comment]
This issue is addressed by the decision to remove namespaces from the API as noted in #562. The API will only be able to access collections (tables) within a single keyspace defined at deployment time.
