### ISSUE TITLE
Errors in response

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#350]
If there is an error thrown during deserialization of commands, response has array of errors as below. The error message in index 0 adds no value. In my opinion it needs to be removed. 
Also the error code is missing on the raised error, in this case expecting `"errorCode" : INVALID_FILTER_EXPRESSION`

`{
    "errors": [
        {
            "message": "$in operator must have at least one value (through reference chain: io.stargate.sgv2.jsonapi.api.model.command.impl.FindOneCommand[\"filter\"])",
            "exceptionClass": "JsonMappingException"
        },
        {
            "message": "$in operator must have at least one value",
            "exceptionClass": "JsonApiException"
        }
    ]
}`

@ivansenic @amorton @tatu-at-datastax

**Comment by tatu-at-datastax** [comment]
@ivansenic This sounds good to me -- we can re-visit this if need be, but I agree that ability to have multiple failures is useful; and in cases we don't want that, avoiding adding (or suppressing) cause makes sense.
Maybe we can also see if suppressing duplicate failures makes sense (literally same fail message) or something.
