### ISSUE TITLE
Change JSON API default port number

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#381]
We are currently using port 8080 as the default port number for JSON API. Since this tends to be a frequently used value, we should change this to reduce the possibility of collisions. Something like 8083 could work.

We will also want to make changes to downstream locations including docker-compose scripts in this repo and other repos like stargate-mongoose and stargate-mongoose-sample-apps.

**Comment by maheshrajamani** [comment]
@jeffreyscarpenter Currently JsonApi is deployed in astra with port #8181. Will use the same port as default.
