### ISSUE TITLE
JSON API should identify itself to bridge as jsonapi

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#387]
JSON API is currently identifying itself as `rest` when connecting to the bridge. It should be identifying itself as a unique new API `jsonapi`.

This primarily has implications for deploying JSON API in AstraDB. The current state would have JSON API leveraging on the authorizations that users would typically get when creating the "default token" for their database (the "REST API" permission is automatically enabled). 

It might be a good idea to allow the value to be configurable to reduce the need to change multiple repos in lockstep. The Stargate repo should probably also have the value `jsonapi` added to the [SourceAPI](https://github.com/stargate/stargate/blob/main/coordinator/authnz/src/main/java/io/stargate/auth/SourceAPI.java) enumeration.

**Comment by jeffreyscarpenter** [comment]
Fixed in #2644

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter This can be closed now, right?
