### ISSUE TITLE
`findOneAndUpdate()` seems to not return result if no updates to apply

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#390]
Send the following commands to jsonapi and you'll see that `findOneAndUpdate()` returns no results, even though there's a document that matches.

```
{
  "deleteMany": {
    "filter": {}
  }
}

{
  "insertMany": {
    "documents": [
      {
        "username": "a"
      }
    ]
  }
}

{
  "findOneAndUpdate": {
    "filter": {},
    "update": {
      "$set": {
        "username": "a"
      }
    },
    "options": {
      "returnDocument": "before"
    },
    "sort": {
      "username": 1
    }
  }
}
```

Change the last command to the following and a document is returned.

```
{
  "findOneAndUpdate": {
    "filter": {},
    "update": {
      "$set": {
        "username": "aaa"
      }
    },
    "options": {
      "returnDocument": "before"
    },
    "sort": {
      "username": 1
    }
  }
}
```

**Comment by maheshrajamani** [comment]
@vkarpov15 If there is no update to the document, the api currently doesn't return document. Will make the change to return document in this scenario too.

**Comment by maheshrajamani** [comment]
@vkarpov15 I believe this behavior is required for `findOneAndReplace()` api too?

**Comment by vkarpov15** [comment]
@maheshrajamani yes, `findOneAndReplace()` as well. Although it looks like `findOneAndReplace()` isn't affected - the following series of commands seems to result in a document being returned from `findOneAndReplace()`:

```
{
  "deleteMany": {
    "filter": {}
  }
}

{
  "insertMany": {
    "documents": [
      {
        "username": "a"
      }
    ]
  }
}

{
  "findOneAndReplace": {
    "filter": {},
    "replacement": {
      "$set": {
        "username": "a"
      }
    },
    "options": {
      "returnDocument": "before"
    },
    "sort": {
      "username": 1
    }
  }
}
```
