### ISSUE TITLE
Support `deleteOne()` and `updateOne()` with `sort`

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#396]
The following command:

```
{
  "deleteOne": {
    "filter": {
      "_id": "0001f363-a2d7-440d-aeb1-54855be43440"
    },
    "sort": {
      "username": -1
    }
  }
}
```

throws the following error:

```
Error: Command "deleteOne" failed with the following errors: [{"message":"Unrecognized field \"sort\" (class io.stargate.sgv2.jsonapi.api.model.command.impl.DeleteOneCommand), not marked as ignorable (one known property: \"filter\"])\n at [Source: (ByteArrayInputStream); line: 1, column: 79] (through reference chain: io.stargate.sgv2.jsonapi.api.model.command.impl.DeleteOneCommand[\"sort\"])","exceptionClass":"UnrecognizedPropertyException"}]
```

I'm not sure how complex it is to support `deleteOne()` with sort, and this isn't high priority. But given that `findOneAndDelete()` supports `sort`, I think it would also be good to support `deleteOne()` with `sort`.

**Comment by maheshrajamani** [comment]
Adding sort for DeleteOne is not complex, i can add it. Is it part of what mangoose api already support? I did not add because it documentation [here](https://mongoosejs.com/docs/api/query.html#Query.prototype.setOptions():~:text=The%20following%20options%20are%20only%20for%20find()%3A) refers sort only available for find.

Also let me know if this is required for deleteMany, UpdateOne and UpdateMany commands too?

**Comment by tatu-at-datastax** [comment]
Since it looks (as per @maheshrajamani's link above) that this is not supported for non-find operations,  is this something implemented on Mongoose side? Or is the doc linked-to incorrect or out-of-date?

**Comment by vkarpov15** [comment]
@tatu-at-datastax the Mongoose docs are incorrect, you can use `sort()` with `deleteOne()`. I pushed a commit to fix that, it will go live when Mongoose 7.1.0 is released.

**Comment by tatu-at-datastax** [comment]
@vkarpov15 Ok.

**Comment by maheshrajamani** [comment]
@vkarpov15 Do we need to support sort in deleteMany, updateOne and updateMany commands too?

**Comment by vkarpov15** [comment]
@maheshrajamani `updateOne()` yes. `deleteMany()` and `updateMany()` no.

**Comment by maheshrajamani** [comment]
Ok got it. I will use the same issue to support for updateOne too.
