### ISSUE TITLE
JSON API Logging

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#404]
Currently the JSON API only logs a bit of info on startup (driven by Quarkus), and nothing really after that. 

We need to determine what logging JSON API will do, at a minimum it seems like there should be some error conditions that are logged. 

Would be useful to investigate what logging we have for other v2 APIs for comparison. For example, I seem to remember that other APIs are logging health check requests.

**Comment by ivansenic** [comment]
I think we should log:

* retries on the warn level
* errors on the error level, if those are server-side errors
* all unexpected situations, LTW failures, etc

**Comment by jeffreyscarpenter** [comment]
Sounds good to me
