### ISSUE TITLE
Performance tests returning bad status code errors

### ISSUE THREAD

**Issue by ivansenic** [stargate/jsonapi#422]
The performance test are printing logs about the mismatched status code:

```
 2203081 WARN  [httpjsonapicrudbasic_default_write:013] ERRORS       error with cycle 615435 errmsg: io.nosqlbench.adapter.http.errors.InvalidStatusCodeException: Server returned status code '504' which did not match ok_status '2..'
```

Example run: https://github.com/stargate/jsonapi/actions/runs/4933013286

**Comment by ivansenic** [comment]
@maheshrajamani could this what I wrote be thre?

**Comment by maheshrajamani** [comment]
> @maheshrajamani could this what I wrote be thre?

I did not understand the question here. 504 is because the coordinator is timing out.

**Comment by ivansenic** [comment]
Uf I read it as 404.. Will adapt the wording..

**Comment by Yuqi-Du** [comment]
> > @maheshrajamani could this what I wrote be thre?
> 
> I did not understand the question here. 504 is because the coordinator is timing out.


Reinvestigate in 504 error.

Reproduce:
I create a vector table(1536) with JSONAPI, having 60000 documents in it.
If I do find by vsearch with 100 threads, each threads run find task 100 times.
There will be one or two 504 error if I do this multiple times, the probability is very low.
And I think it really depends on coordinator state.
