### ISSUE TITLE
Validation for vector search

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#460]
1. Vector value array can’t be empty
2. All values of the vector must be valid number
3. If value is null means value is unset, remove the value from the index
4. Skip option not allowed in case of vector search.
5. Limit while using vector search should be less than or equal 1000.

**Comment by vkarpov15** [comment]
6. Vector value array length must be exactly equal to the vector dimensions set in `createCollection()`
7. Can't use `$push`, `$pop`, `$addToSet`, `$rename` update operators with `$vector`

Also, does `$vector` always explicitly need to be set? Or is it valid to store a document with no `$vector` property?

**Comment by maheshrajamani** [comment]
> Also, does `$vector` always explicitly need to be set? Or is it valid to store a document with no `$vector` property?

Document could be stored without a $vector field.
