### ISSUE TITLE
Include vector similarity in vector search result

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#463]
Ideally there should be a way to return the computed similarity between the search vector and the result vectors.

**Comment by maheshrajamani** [comment]
Returning similarity score will be supported only for find and findOne commands using projection clause. By default similarity score won't be returned in response. $similarity_score will be reserved field name that can be used in projection to get the similarity function score.

{
  "find": {
    "sort" : {"$vector" : [0.15, 0.1, 0.1, 0.35, 0.55]},
    "projection" : {"_id" : 1, $similarity_score : 1}
  }
}

Response:

{
  "data": {
     "document": {
       "_id": "1",
       "$similarity_score": 1.25
     }
  }
}

**Comment by vkarpov15** [comment]
Minor nitpick: I'd prefer to make the name `$distance` or `$score` or `$similarity`, something that is one word so we don't have to worry about snake_case vs camelCase. Admittedly this is a tiny amount of friction, but I think it is friction that we can reasonably avoid.

**Comment by maheshrajamani** [comment]
No issues @vkarpov15 . I will have it as $similarity.
