### ISSUE TITLE
DataStoreConfig is not produced, use DataStoreProperties instead

### ISSUE THREAD

**Issue by Yuqi-Du** [stargate/jsonapi#508]
In JSON API, we need to examine things like SAI, Vector Search are supported by cassandra backend or not.
When create collection ([CreateCollectionCommandResolver](https://github.com/stargate/jsonapi/blob/main/src/main/java/io/stargate/sgv2/jsonapi/service/resolver/model/impl/CreateCollectionCommandResolver.java)), we use DataStoreConfig. However, the injected dataStoreConfig object is the default one and can not respond to backend change.

**Comment by tatu-at-datastax** [comment]
@Yuqi-Du I am not against the change, but it would be good to figure out why `DataStoreConfig` has wrong information, and if that could be fixed. Or, alternatively, if we could completely get rid of `DataStoreConfig` use if that does not and can not work. It seems risky to have 2 very similar looking configuration containers as that can lead to problems.

@maheshrajamani do you remember background on why we might have this duplication?

**Comment by maheshrajamani** [comment]
@Yuqi-Du I remember testing DataStoreConfig against dse-6.8 and dse-next. it worked fine, are you sure it doesn't work?

> @maheshrajamani do you remember background on why we might have this duplication?

@tatu-at-datastax Not sure. Looking at the code it might be to override through properties.

**Comment by tatu-at-datastax** [comment]
Ah. Maybe `DataStoreConfig` existed before and `-Properties` was added to allow overrides.

**Comment by Yuqi-Du** [comment]
Thanks guys. 
DataStoreConfig is never been produced with correct values against the persistence, it worked to DSE-next since DataStoreConfig enables vectorsearch. But for dse-6.8, jsonapi will still think backend support vectorsearch, and raise errors when proceeding.

**Comment by jeffreyscarpenter** [comment]
This is no longer relevant since we have removed dependence on bridge
