### ISSUE TITLE
findOne filtering by `$vector` returns no results

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#516]
The following query returns no results:

```
{
  "findOne": {
    "filter": {
      "$vector": [
        100,
        1
      ]
    },
    "options": {}
  }
}
```

But executing the following:

```
{
  "find": {
    "filter": {}
  }
}
```

Returns:

```
[
  {
    _id: new ObjectId("64ea8e193e3aec5cd0b356b2"),
    '$vector': [ 1, 100 ],
    name: 'Test vector 1',
    __v: 0
  },
  {
    _id: new ObjectId("64ea8e193e3aec5cd0b356b3"),
    '$vector': [ 100, 1 ],
    name: 'Test vector 2',
    __v: 0
  }
]
```

Are you able to query by exact match for `$vector`?

**Comment by tatu-at-datastax** [comment]
@vkarpov15 Trying this out with `cqlsh` I think the answer is "no" -- indexed Vector values can only be used for ANN search:

```
select * from vector_test where val = [1, 0.1, 0];

InvalidRequest: Error from server: code=2200 [Invalid query] message="Vector indexes only support ANN queries"
```

But I guess it is odd if we get no error or anything via JSON API.

**Comment by tatu-at-datastax** [comment]
Ok. No failure yet -- will add validation of filter, to give meaningful fail message on attempt to filter on `$vector`.
