### ISSUE TITLE
findOneAndDelete by vector has NPE issue in concurrent situation

### ISSUE THREAD

**Issue by Yuqi-Du** [stargate/jsonapi#517]
`{
    "findOneAndDelete": {
        "sort": {
            "$vector": [xxxxxx]
        }
    }
}`
When I am doing `findOneAndDelete by vector` performance testing, I noticed that not all responses are correct following `.*\"deletedCount\":[0,1].*` pattern.

Then I write a test code with just 20 threads posting `findOneAndDelete by vector` to JSONAPI(enough data to delete). In the result, there are two other unexpected responses.
<img width="944" alt="image" src="https://github.com/stargate/jsonapi/assets/138714577/5e3666c3-54c2-408b-a26d-6f5d72daa87c">

The CAS one is not from JSON API.
NPE is from JSON API which in [DeleteOperation.java](https://github.com/stargate/jsonapi/blob/main/src/main/java/io/stargate/sgv2/jsonapi/service/operation/model/impl/DeleteOperation.java)
<img width="941" alt="image" src="https://github.com/stargate/jsonapi/assets/138714577/5fb8eee8-039b-4132-b48a-8c8c0b65383b">

Although all three responses have 200 code, but may have problems here.

**Comment by tatu-at-datastax** [comment]
Quick note: you are right that status code of `200` does not mean there is no problem: it just means service itself caught the exception and handled it.

**Comment by tatu-at-datastax** [comment]
Was fixed by #518
