### ISSUE TITLE
Add metrics tagging for vector functionality

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#526]
Add tagging to the `command_processor_process_seconds_count` metrics to indicate whether calls include vector functionality (probably `true/false` makes the most sense).

**Comment by maheshrajamani** [comment]
There will be 2 tags added.

1. `vector.enabled` - This will suggest if vector storage is enabled for the collection.
2. `search.type` - This can have 3 values denoting what kind of document search was performed
      -  VECTOR_SEARCH
      - VECTOR_SEARCH_WITH_FILTERS
      - OTHER
