### ISSUE TITLE
[Vectorize] Remove $vectorize field in the document 

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#532]
If an update come in for $vector field directly, remove $vectorize field in the document if it exist.

@vkarpov15 FYI

**Comment by Yuqi-Du** [comment]
"remove" means just set "$vectorize" field as empty string, or delete "$vectorize" field in the whole document?

**Comment by maheshrajamani** [comment]
If the existing document in the DB is, in that case $vector field would have been generated using $vectorize field data
`{
  "id" : "1",
  "name" : "test",
  "$vectorize" : "Test data",
  "$vector" : [0.25,0.25,0.25]
}`

and we get a update clause as {"$set" : {"$vector" : [0.11,0.11,0.11]}} where update is directly to $vector field. This should remove $vectorize field too when $vector field is updated. Post update document should look as:
`{
  "id" : "1",
  "name" : "test",
  "$vector" : [0.11,0.11,0.11]
}`

**Comment by vkarpov15** [comment]
This is a good suggestion, makes a lot of sense. `$vectorize` and `$vector` need to stay in sync.
