### ISSUE TITLE
includeSimilarity option doesn't seem to work with `findOne()`

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#558]
Re: #500 . Sending the following command:

```
{
  "findOne": {
    "filter": {},
    "options": {
      "includeSimilarity": true,
      "sort": {
        "$vector": [
          1,
          99
        ]
      }
    }
  }
}

```

gives me back document without `$similarity`:

```
{
  "data": {
    "document": {
      "_id": "6521a52380e9bef986ccdb35",
      "$vector": [
        1,
        100
      ],
      "name": "Test vector 1",
      "__v": 0
    }
  }
}

```

When I replace `findOne` with `find`, I get back documents with `$similarity` as expected. Based on my reading of #500, `findOne()` should also support `includeSimilarity` option.

**Comment by maheshrajamani** [comment]
@vkarpov15 The sort option has to be outside the options.

**Comment by vkarpov15** [comment]
@maheshrajamani I tried both, the following still doesn't return `$similarity`:

```
{
  "findOne": {
    "filter": {},
    "options": {
      "includeSimilarity": true
    },
    "sort": {
      "$vector": [
        1,
        99
      ]
    }
  }
}
```

Result:

```
{
  "data": {
    "document": {
      "_id": "6529520aba190a47db5d1309",
      "$vector": [
        1,
        100
      ],
      "name": "Test vector 1",
      "__v": 0
    }
  }
}
```

The equivalent `find` command does return `$similarity`:

```
{
  "find": {
    "filter": {},
    "sort": {
      "$vector": [
        1,
        99
      ]
    },
    "options": {
      "includeSimilarity": true
    }
  }
}

```

**Comment by maheshrajamani** [comment]
I tried a test it's working fine for findOne. @kathirsvn Can you check if this is an issue in stargate-mangoose?

**Comment by kathirsvn** [comment]
I created an issue in stargate-mongoose for this https://github.com/stargate/stargate-mongoose/issues/145. Basically, the find and findOne options doesn't pass the includeSimilarity score option flag to JSON API (it's not in the list of supported internal options). Passing `$similarity : 1` in `projection` [works](https://github.com/stargate/stargate-mongoose/blob/a63217d905db3ebaff4608e18e714f1ebfe74772/tests/driver/api.test.ts#L810).

**Comment by vkarpov15** [comment]
@kathirsvn I have PR here: https://github.com/stargate/stargate-mongoose/pull/143 that makes stargate-mongoose pass `includeSimilarity` option. Even with those changes, `includeSimilarity` doesn't seem to work with `findOne()`. Does work with `find()` though.

**Comment by vkarpov15** [comment]
@kathirsvn @maheshrajamani  see test failure here: https://github.com/stargate/stargate-mongoose/actions/runs/6519099591/job/17705217827?pr=143 . I tried a bunch of different ideas: bumping JSON API version, removing the `filter` clause to match [this test](https://github.com/stargate/jsonapi/blob/5e278ddde1a07e4249b835aaa34a33afbfd21e6f/src/test/java/io/stargate/sgv2/jsonapi/api/v1/VectorSearchIntegrationTest.java#L1559), swapping order of `sort` and `options` keys. Still no luck in getting `findOne()` to return `$similarity` if setting `includeSimilarity` option.

Here's the output containing the JSON API command and the result:

```
{
  "findOne": {
    "sort": {
      "$vector": [
        1,
        99
      ]
    },
    "options": {
      "includeSimilarity": true
    }
  }
}

{
  "document": {
    "_id": "652ad62075dae62c59b00881",
    "$vector": [
      1,
      100
    ],
    "name": "Test vector 1",
    "__v": 0
  }
}
```

**Comment by vkarpov15** [comment]
Fixed by @kathirsvn in https://github.com/stargate/stargate-mongoose/pull/143/commits/9ed37b4cbc9b6e180acdd4ca3e07bf1a037d319b . The issue was that one layer below where I was looking in stargate-mongoose was stripping out the `includeSimilarity` option.
