### ISSUE TITLE
Remove namespace from the API

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#562]
The current design of JSON API includes the concept of a namespace which contains collections. Namespaces are implemented as Cassandra keyspaces, and collections as Cassandra tables. The concept of namespaces seems to cause more confusion than benefit as most users don't need the concept of additional grouping of document collections. We propose to remove the concept of namespace from the JSON API. Instead, the API will abstract keyspace usage entirely, managing that as an implementation detail. 

This will have widespread impact on the JSON API implementation, tests as well as downstream artifacts including documentation, postman collections, and clients sch as stargate-mongoose, etc. However the changes should be relatively simple.

**Comment by JeremiahDJordan** [comment]
I do not think it should be removed completely?  It should be an optional parameter.  The "Default Namespace" should be a config option of some kind.  You could either use the cluster name from the C* config, or have some other setting.

**Comment by jeffreyscarpenter** [comment]
The default keyspace should be configurable via a property. It should default to `default_keyspace`.
It may also make sense to have another property which controls whether the API will create the default keyspace if it does not exist.

**Comment by maheshrajamani** [comment]
Following are the changes required to remove namespace.

1. Add namespace configuration to application.yaml and OperationsConfig.java
2. Remove GeneralResource.java, it currently handles the namespace related commands.
3. Rename NamespaceResource as GeneralResource
4. Remove namespace from the url of the new GeneralResource, it will now be only /v1
5. Remove namespace from the url of the new CollectionResource, it will now be only /v1/{collectionName}
6. In the SchemaCache, change the methods to get the namespace name from OperationsConfig and set it to CommandContext.
7. Change all test cases to remove the namespace from the url
