### ISSUE TITLE
Vector options name change

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#567]
Change the name for vector options in createCollection command:
1) `size` -> `dimension` and 
2) `function` -> `metric`

**Comment by tatu-at-datastax** [comment]
`dimensions` sounds reasonable, although I'd probably try to see what other vector DBs use.

Not sure about `metric`, if that means "cosine" etc, then -1 on that change. Would need to explain why that is not worse name than "function".

**Comment by vkarpov15** [comment]
Pinecone uses "dimensions" and "metric":

![image](https://github.com/stargate/jsonapi/assets/1620265/1c74066d-fe9a-495c-85eb-19220310a20d)

Chroma uses "dimension" and "distance"

![image](https://github.com/stargate/jsonapi/assets/1620265/a8015c4a-d4c7-4544-8795-196878d19059)

![image](https://github.com/stargate/jsonapi/assets/1620265/4f3e6d1e-49bc-490a-89b9-be30b3e06cd8)

MongoDB uses "dimensions" and "similarity"

![image](https://github.com/stargate/jsonapi/assets/1620265/34a60d7b-9837-439c-a4fa-595c6676372e)

So there's precedent for using "dimension" and "metric". I think I would prefer "dimensions" and "similarity", but I think that's more of a "marketing" decision. "Metric" sounds more academic and professional, "similarity" sounds more colloquial and pragmatic IMO.

**Comment by jeffreyscarpenter** [comment]
Can we continue to support the old property names for a short time for backward compatibility?

**Comment by jeffreyscarpenter** [comment]
Do we also need to make similar changes on stargate-mongoose?

**Comment by tatu-at-datastax** [comment]
Depending on how we map names, Jackson has `@JsonAlias` annotation to support alternative names. But it is also possible we just extract properties by name, and if so could add fallbacks too (get new property first; if none, get old one).

**Comment by kathirsvn** [comment]
> Do we also need to make similar changes on stargate-mongoose?

Yes, we will have to make corresponding changes in stargate-mongoose as well. I just created an issue for the same https://github.com/stargate/stargate-mongoose/issues/147
