### ISSUE TITLE
Replace `X-Cassandra-Token` with `Token`

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#569]
We need to rename the header that we are using for accessing the JSON API. There is no need to reference Cassandra in this context. Will add a note with the new name when we have decided on it.

**Comment by jeffreyscarpenter** [comment]
The new name will be "Token". We will also support "X-Cassandra-Token" for backward compatibility.

**Comment by maheshrajamani** [comment]
@jeffreyscarpenter For this we need to just start the json api with this VM arg set., https://github.com/stargate/stargate/blob/main/apis/sgv2-quarkus-common/CONFIGURATION.md#:~:text=stargate.auth.header%2Dbased.header%2Dname
