### ISSUE TITLE
Pagination name discrepancy "nextPageState" vs "pagingState"

### ISSUE THREAD

**Issue by hemidactylus** [stargate/jsonapi#596]
There is a slight discrepancy in the current name of the parameters around pagination:
- users receive `nextPageState`,
- but they must supply `pagingState` in their subsequent calls.

It's a small thing, yet it can be somewhat surprising and make things a tad less obvious from the user's perspective, which probably wonders why it is not consistently "paging" or "page" but half-and-half.

_(I see the only other issue referencing the name of these parameters is #260 which however is quite old and does not refer to this same point, so I opened a new issue here. Feel free to close if not considered relevant :) )_

**Comment by tatu-at-datastax** [comment]
I am not sure which way to go here: both terms are quite widely used (as per Google searches), and Cassandra Drivers appear to use "paging state":

```
// from https://niels.nu/blog/2016/cassandra-resultset-paging:
select.setPagingState(PagingState.fromString(page));
```

but I agree that we should use one form consistently. We can also leave the alternative form as alias on short term.

@amorton @jeffreyscarpenter @maheshrajamani Do you agree with Val that we should unify to "page state" (over "paging state")?
