### ISSUE TITLE
Metrics for the SessionCache

### ISSUE THREAD

**Issue by amorton** [stargate/jsonapi#646]
This is a placeholder so we do not forget to add metrics to the Session Cache. 

@kathirsvn  we thought there was an existing issue for this but could not find one. Can you reply on here and let us know.

**Comment by kathirsvn** [comment]
@amorton I missed to create an issue for this and thanks for creating the same.

**Comment by kathirsvn** [comment]
Fixed by https://github.com/stargate/jsonapi/pull/689
