### ISSUE TITLE
401 instead of 500 for bad credentials

### ISSUE THREAD

**Issue by kathirsvn** [stargate/jsonapi#707]
Currently, passing bad credentials is returning 500 instead of 401.

**Comment by Yuqi-Du** [comment]
Hi Kathir, interested in how to find the right error mapping under this Astra environment.
If possible, please attach some info when you solve this.
Thank you

**Comment by tatu-at-datastax** [comment]
Getting 500 would suggest there may be unexpected exception on server side, being translated to generic "Server fail" problem? If so, maybe there is a stack trace include in description?
