### ISSUE TITLE
Set Error codes in CommandResult.Error

### ISSUE THREAD

**Issue by kathirsvn** [stargate/jsonapi#720]
>         
> One question: is there any way to be able to get `errorCode` to be added in `CommandResult.Error` returned? There are discussion with Client-side folks to be able to rely more on `errorCode` for classifying types of failures.
> But as things are, only `JsonApiException` produces `ErrorCode` values.
> 
> I guess this is a bigger question and maybe not something to tackle for this PR, but I thought I'd mention it for future reference.

_Originally posted by @tatu-at-datastax in https://github.com/stargate/jsonapi/issues/715#issuecomment-1847589578_

**Comment by kathirsvn** [comment]
May be `@JsonIgnore` needs to be removed here?
https://github.com/stargate/jsonapi/blob/9539b85f303845b1fa55c44ae369187e298b153a/src/main/java/io/stargate/sgv2/jsonapi/api/model/command/CommandResult.java#L177

cc: @tatu-at-datastax @maheshrajamani

**Comment by tatu-at-datastax** [comment]
@kathirsvn That would indeed include `Response.Status` in serialization, but I think that seems to be enumeration of HTTP response codes:

```
    public static enum Status implements StatusType {
        OK(200, "OK"),
        CREATED(201, "Created"),
```

which is not quite what we want, I think.
