### ISSUE TITLE
Command-level logging

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#741]
Let's add logging at the DEBUG level for each command. 

This should contain the name of the command as already used in the CommandProcessor metrics, for example: `FindCommand`, `DeleteManyCommand`, etc.

The logging should also include pertinent data per call such as:

- tenant ID, namespace, collection name
- size of incoming/outgoing document(s)
- for `insertMany`, `updateMany`, `deleteMany`, the number of documents in the request, and the number of documents handled successfully.
- the duration of the request (maybe, because it is already captured in metrics)

**Comment by amorton** [comment]
Make these metrics first, logging as a secondary concern.

**Comment by jeffreyscarpenter** [comment]
@amorton we already have the CommandProcessor metrics. The attributes I've described here would not make good tags on those metrics as they would blow up the cardinality.

**Comment by tatu-at-datastax** [comment]
Couple of quick comments:

* Size of incoming request, outgoing request, may be difficult to get out from code as-is, given that Quarkus handles deserialization of requests and serialization of responses. If we really want these, we could probably change things to handle this instead of Quarkus but that would be bigger, invasive changes.
* Duration: not super complicated to wrap but bit invasive as well

**Comment by jeffreyscarpenter** [comment]
Good points @tatu-at-datastax. I suppose we could enable [HTTP request logging](https://quarkus.io/guides/http-reference#configuring-http-access-logs) if desired to get the timing and sizing information. If we turned that on that it would probably be pretty simple to correlate that with corresponding command processor logging.

**Comment by tatu-at-datastax** [comment]
@jeffreyscarpenter Agreed.

**Comment by kathirsvn** [comment]
I think we can extend this feature from quarkus-common to achieve what we want.

https://github.com/stargate/stargate/blob/main/apis/sgv2-quarkus-common/CONFIGURATION.md#additional-logging-configuration
https://github.com/stargate/stargate/pull/2754

With below simple config changes on the JSON API application.yaml file, I was able to print the request information
```yaml
stargate:
  api:
    logging:
      enabled: true
      enabled-error-codes: 200
      request-body-logging-enabled: true

 quarkus:
   log:
     category:
        "io.stargate.sgv2.api.common.logging.LoggingFilter":
          level: DEBUG
```

```log
DEBUG [vert.x-eventloop-thread-0] 2024-01-02 12:40:33,812 LoggingFilter.java:66 - REQUEST INFO :: tenant-unknown 200 POST /v1/cycling {
  "createCollection": {
    "name": "events$%#"
  }
}
```

We also have additional options like "log only for certain error codes" available in this. If we agree to use this I can create a PR to extend this to have more JSON API specific options to print size of incoming/document size etc.

**Comment by jeffreyscarpenter** [comment]
@kathirsvn this is great, I did not realize we already had this capability. I think we need to default to not logging the request body. Would it be possible to enable request body logging for only a specific tenant?

**Comment by tatu-at-datastax** [comment]
Another thing is that if we already add command name as context value (something logger can access, similar to tenant-id), logging that would be useful and reduce need to log request body.

**Comment by kathirsvn** [comment]
> @kathirsvn this is great, I did not realize we already had this capability. I think we need to default to not logging the request body. Would it be possible to enable request body logging for only a specific tenant?

Yes, request body logging is not enabled by default.

**Comment by jeffreyscarpenter** [comment]
Can we also log the ErrorCode if present?
