### ISSUE TITLE
Catch and re-throw Java CQL Driver fail exceptions as `JsonApiException` with appropriate `errorCode`s

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#751]
Currently failures caught by JSON API itself are reported using `JsonApiException`, which takes one of `ErrorCode` enum values, as well as regular Exception `message`. Error code gets included in response message as `errorCode` property, and allows clients to classify failures without having to decode possibly varying (including over time) textual message.
This is useful thing to have.

But same is not currently being done for Exceptions thrown by Java CQL driver which is used to talk to the storage backend (via Coordinator now, possibly directly in future): these exceptions result in error messages, but without `errorCode`.
We need to start catching these exceptions and throwing `JsonApiException`s with appropriate `errorCode`s -- or equivalent handling that results in `errorCode` being included in response message returned to caller.

**Comment by jeffreyscarpenter** [comment]
The following CQL Driver errors have been observed in testing:

- AllNodesFailedException (on CreateCollectionCommand and FindCollectionsCommand)
- ClosedConnectionException (on CountDocumentsCommand, CreateCollectionCommand, DeleteCollectionCommand, FindCommand)
- NoNodeAvailableException (on CreateCollectionCommand, DeleteCollectionCommand, FindCommand, FindOneCommand, InsertManyCommand)
- ReadFailureException (on CountDocumentsCommand, FindCommand)

These exceptions all need to be caught and mapped to JsonApiException with an appropriate error code. Recommend looking at log data to see if there are different causes for each exception that would result in the need for distinct error codes. For example, all instances of AllNodesFailedException that I have observed have an embedded authentication error. (The service does return HTTP 401 not authorized in that case and not a JSON API error code, so it's not a perfect example.)

Note: The details on which command each exception occurred are for information purposes and not assumed to be exhaustive of what exceptions could possibly occur on a given operation.

**Comment by tatu-at-datastax** [comment]
It seems likely that solving this issue is an iterative process; so important to incrementally map exceptions even if exhaustive search not possible.
`AllNodesFailedException` tricky since it's a "combo" exception so requires "peeling of onion" (making decision on one or more of underlying root cause exceptions).

**Comment by jeffreyscarpenter** [comment]
> It seems likely that solving this issue is an iterative process; so important to incrementally map exceptions even if exhaustive search not possible. `AllNodesFailedException` tricky since it's a "combo" exception so requires "peeling of onion" (making decision on one or more of underlying root cause exceptions).

Exactly. We should explore other exceptions to see if they also have this feature of possibly embedding other exceptions or having separate messages for distinct failures.

**Comment by Yuqi-Du** [comment]
| Exception                   | Commands                                               |
|-----------------------------|--------------------------------------------------------|
| DriverTimeoutException      | CreateCollectionCommand                                |
| NoNodeAvailableException    | CreateCollectionCommand                                |
|                             | FindCommand                                             |
| AllNodesFailedException     | CreateCollectionCommand                                |
|                             | FindCollectionsCommand                                 |
|                             | FindNamespacesCommand                                   |
| InvalidQueryException       | CountDocumentsCommand                                   |
|                             | CreateCollectionCommand                                |
|                             | DeleteCollectionCommand                                |
|                             | FindCommand                                             |
|                             | InsertManyCommand                                       |
|                             | InsertOneCommand                                        |
| ClosedConnectionException   | CountDocumentsCommand                                   |
|                             | CreateCollectionCommand                                |
|                             | DeleteCollectionCommand                                |
|                             | FindCommand                                             |
| ReadFailureException         | CountDocumentsCommand                                   |
|                             | FindCommand                                             |
| UnauthorizedException        | CreateCollectionCommand                                |
| ServerError                  | CreateCollectionCommand                                |




+1 Should incrementally mapping these
