### ISSUE TITLE
Reduce max Vector dimension limit from 10,000 to 4,096 not to fail due to SAI/ANN limit

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#772]
Currently JSON API limits maximum Vector (`$vector`) dimension to rather high limit -- 16,000 -- which was simply chosen as "big enough not to matter". But it appears that there is a true limit as per:

https://github.com/riptano/VECTOR-SEARCH/issues/73

which limits indexable entry to 16kB, and with `float`-vector (4 bytes for `float32`) it means actual upper max dimension of 4,096.
So let's align this limit so JSON API can validate creation without hitting DB guardrails (esp. since test DB may not even have guardrails enabled).

New limit should still be above sizes needed in practice (f.ex, OpenAI's "standard" 1,536 ).

**Comment by vkarpov15** [comment]
4096 should be fine: [here's a nice read on embedding sizes from an AI eng perspective](https://medium.com/@matti.kwan/finding-the-optimal-number-of-dimensions-for-word-embeddings-f19f71666723). The only place I've been able to find a model that outputs embeddings longer than 4096 is [an outdated OpenAI model that would output embeddings of length 12000](https://openai.com/blog/new-and-improved-embedding-model). So while it is possible we will need to support larger embeddings in the future, it isn't urgent.

**Comment by tatu-at-datastax** [comment]
Thank you for sanity check @vkarpov15 . Good to know our thinking was not wrong here.
