### ISSUE TITLE
INVALID_REQUST error code typo

### ISSUE THREAD

**Issue by vkarpov15** [stargate/jsonapi#796]
Error code here has a typo: https://github.com/stargate/jsonapi/blob/03daa7e4b5697eca1477de4ce911bb4f43484588/src/main/java/io/stargate/sgv2/jsonapi/exception/ErrorCode.java#L28, leads to the following error message showing up:

```
  errors: [
    {
      message: 'ANN ordering by vector requires the column to be indexed',
      errorCode: 'INVALID_REQUST'
    }
  ],

```

**Comment by tatu-at-datastax** [comment]
I think this was fixed by PR, closing.
