### ISSUE TITLE
Improve error message when collection name omitted

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#800]
A user reported the following error when executing a command on the JSON API:

```
{"errors":[{"message":"Could not resolve type id 'insertOne' as a subtype of `io.stargate.sgv2.jsonapi.api.model.command.NamespaceCommand`: Class `io.stargate.sgv2.jsonapi.api.model.command.impl.InsertOneCommand` not subtype of `io.stargate.sgv2.jsonapi.api.model.command.NamespaceCommand`\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled);
```

The problem is that the insertOne operation is an operation on the collection resource, but the collection name was not included on the URL path (i.e. /api/json/v1/<namespace>/<collection>). Let's see if we can give a better error message if a collection command is requested on the namespace resource.

**Comment by tatu-at-datastax** [comment]
Would it be possible to add specific URL user used to simplify reproduction?

**Comment by Yuqi-Du** [comment]
What this PR does:
JSON API should detect the mismatch of provided command with url path.

e.g. 1
{{base_json_url}}{{json_api}}/namespace

{
    "find":{}
}
should prompt No 'find' command found as NamespaceCommand

e.g. 2
{{base_json_url}}{{json_api}}/namespace/collection

{
    "randomGuy":{}
}
should prompt No 'randomGuy' command found as CollectionCommand

e.g. 3
{{base_json_url}}{{json_api}}/namespace/collection

{
    "createNamespace":{}
}
should prompt No 'createNamespace' command found as CollectionCommand
