### ISSUE TITLE
Add validation of `"options"` property of `createCollection` command to avoid silent failures

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#828]
Currently there are 2 valid sub-properties to use with `createCollection` command: "vector" and "indexing".
Their contents are validated, and if found good, used for adding (or not) of `$vector` columnd (for first) and changing indexing aspects.

But if users adds any other option child property -- possibly (but not only) misspelling one of 2 valid names, like "Vector" (values are case-sensitive) or "index" (instead of "indexing"), collection creation will effectively just ignore such options.

We should validate properties of "options" and report a failure for unknown option (with new `ErrorCode`, similar to `COMMAND_ACCEPTS_NO_OPTIONS`). This is useful for indicating problem back to user.

**Comment by vkarpov15** [comment]
I took a look and confirmed that Mongoose doesn't send any `createCollection()` options by default, so no problems there if JSON API errors out on unknown options.

**Comment by tatu-at-datastax** [comment]
Thank you for confirming, @vkarpov15 .
