### ISSUE TITLE
Implement Array operators $size and $all

### ISSUE THREAD

**Issue by maheshrajamani** [stargate/jsonapi#85]
Implement $size and $all array filter operator condition. 

$size 
Eg:
Match the documents which has an element for the given field which is an array type with size equal to number provided in the filter.
{ "find" : { "filter" : { "field" :  {  "$size" : 2  } }  } }

This will corresponds to CQL where clause as WHERE array_size['field'] = 2

$all 
Eg:
Match the documents which has a array containing all the 
{ "find" : { "filter" : { "column" :  {  "$all" : ["a", "b"] } }  } }

This will corresponds to CQL where clause as WHERE array_contains CONTAINS hash("a") and array_contains CONTAINS hash("b")

**Comment by tatu-at-datastax** [comment]
Why was this reopened? Usually we create new issues for follow-up work.

**Comment by maheshrajamani** [comment]
@amorton Why is this reoped?

**Comment by maheshrajamani** [comment]
Closing the issue, as its already implemented.
