### ISSUE TITLE
Renaming to Data API

### ISSUE THREAD

**Issue by jeffreyscarpenter** [stargate/jsonapi#860]
As part of marketing decisions around General Availability of the API, we renamed it to "Data API" when deploying in Astra. We should perform appropriate renaming on this open source repo, with the goal of having minimal impact to downstream dependencies. 

The following changes are proposed:

- rename this repo from `stargate/jsonapi` to `stargate/dataapi`. GitHub will handle forwarding to the new address.
- update documentation such as the README and spec
- update how the app identifies itself in quarkus
- note that the postman collections for the API have already been renamed
- docker image name to change from `stargateio/jsonapi` to `stargateio/dataapi`. We will tag images with both names on Docker Hub for some duration (2 months?) before retiring the `jsonapi` name.

The following references to `json` or `jsonapi` are proposed to not be changed:

- the URL path `/v1/json...`, as changing would break compatibility for many users and client libraries.
- metrics reporting as `sgv2-jsonapi`
- Source code structure such as 
  - base Java package name `io.stargate.sgv2.jsonapi` 
  - named classes such as `JsonApiException`, `JsonApiMetricsConfig`, etc. 
  - base property name `stargate.jsonapi`

We would target these changes for an early post GA (1.0.0) release such as 1.0.1 or 1.0.2.

**Comment by Yuqi-Du** [comment]
- stargate v2.1 release workflow (has a release event dispatched to JSON API repo)
- deployment related? (serverless-argocd, serverless-platform-charts)
- jsonapi github url referenced by other repos (stargate-mongoose, sample-apps, etc. )
