### ISSUE TITLE
Unclear error message for Bean Validation failures

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/jsonapi#873]
Annotation-based (Bean Validation) input validation is convenient way to add constraints to REST endpoints, but currently produces error messages that are unclear. User reported:

```
{"errors":[{"message":"Request invalid, the field postCommand.command.name not valid: must match \"[a-zA-Z][a-zA-Z0-9_]*\".","exceptionClass":"ConstraintViolationException"}]}
```

where it is unclear what exactly is wrong. This is produced by `ConstraintViolationExceptionMapper` and:

1. Does not enclose `postCommand.command.name` (which is logical name of property for which value is given) in quotes (to indicate it is specific term), but more importantly
2. Does not actually include problematic value in error message

Since (2) is available from `ConstraintViolation`, let's add it, and also wrt (1) add single quotes to make it bit easier to read.

**Comment by maheshrajamani** [comment]
@tatu-at-datastax Can we also drop `postCommand.command` from the begining of the property path?
Instead of `postCommand.command.name` would be better if returned only `name`

**Comment by tatu-at-datastax** [comment]
@maheshrajamani this is provided by Bean Validation framework, but we can definitely post-process it? I agree that full path does not provide any value.

**Comment by tatu-at-datastax** [comment]
What I think I will go with is to drop `postCommand.` prefix: that seems to leave useful information for cases I've looked at.
